### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy._lib.six'

### ISSUE THREAD

**Issue by andrewjong** [fire-rs-laas/fire-rs-saop#17]
Occurs when running `make benchmark`.

The failing import line is line 75 of `python/fire_rs/rbf.py`:
```python
from scipy._lib.six import callable, get_method_function, get_function_code
```

Fix is as simple as doing `pip3 install six` and modifying the line to import six directly, i.e. `from six import ...`.

I can submit a PR later today to fix it.

**Comment by arbimo** [comment]
Thanks for the report !
I would be very happy to merge a PR if you provide one.
