### ISSUE TITLE
Bad performance impact of TrajectorySmoothingNeighborhood

### ISSUE THREAD

**Issue by arbimo** [fire-rs-laas/fire-rs-saop#3]
TrajectorySmoothingNeighborhood seems to have a very high impact on performance.

The presence of this neighborhood tends to increase planning time by a factor 10.
Interestingly, the additional runtime is not located only in this neighborhood but is spread among all neighborhoods.

I suspect this is due to TrajectorySmoothing aggressively cloning plans to decide whether or not to accept a move.
This probably has a very bad impact on the cache, thus impacting the performance of other, seemingly unrelated, code.

**Comment by rafael1193** [comment]
TrajectorySmoothingNeighborhood is no longer used

**Comment by arbimo** [comment]
Then we should remove it from the repository. No point in keeping and maintaining dead code, especially if it comes with surprising performance implications (we can always retrieve from history if needed).
