### ISSUE TITLE
Planning in 3D space

### ISSUE THREAD

**Issue by arbimo** [fire-rs-laas/fire-rs-saop#6]
Here is a list of things that we might want consider in order to plan in a 3D space:

1. [ ] Define what are acceptable altitude for sensing (related to the development of the image acquisition part)
2. [ ] Make insertion neighbourhood aware of altitude. Right now, we assign an altitude when when randomly picking up a cell in the map. However this altitude is not updated when projecting the cell on the fire front (only x and y coordinates are changed). We should probably define default altitude for given predecessor and successor (like it is done for the angle).
 3. [ ] Check that we do not run into a mountain in the middle of a 3D path (this is probably the hardest and most expensive part)
 4. [ ] Consider elevation changes in trajectory optimization
 5. [ ] Allow planning either in 2D or 3D (where 2D will probably be using Dubins3D with fixed elevation).

Implementation wise, point number 2) is probably the most critical for correctness. Point number 5) would be nice to have in order to test both 2D and 3D behaviors in benchmarks.

**Comment by rafael1193** [comment]
- I've been already thinking about, and discussing, (1) for some time and the answer I got is that we should fly as high as possible over ground level. Cameras have so many pixels wrt the DTM that descending gives no advantage wrt to resolution of the mapping. The most important limit is the legal ceiling to fly UAVs, so I think we should always fly at this ceiling. However, the limit is relative to ground level so we have still to consider 3D paths.

- Related to (2) and (4) I agree there yet work to be done

- Point (3) is __hard__. I haven't come with an easy solution yet without simplifying the problem too much.

- Finally, for (5) we should only consider adding some floor and ceiling for segment insertion. If both are the same, the trajectory is flat 😃

**Comment by arbimo** [comment]
Happy to learn about your first point. It will simplify planning and "mountain avoidance". It would be interesting, for a given map, to know what are the min/max altitude for each point of the map.
It would help with point 3) (e.g. answering whether there is a 2D plane that is safe to fly in) and to better understand what are the maximum climbing rate we might need to do.
This in turn might help in understanding the tradeoff between always going for the highest point and limiting unnecessary climbs.
