### ISSUE TITLE
Load benchmark.py arguments from a file

### ISSUE THREAD

**Issue by rafael1193** [fire-rs-laas/fire-rs-saop#7]
Argument list for benchmark.py is getting quite long, we should be doing something to manage this mess.

Several options are availabe:
 - [Python argparse ```fromfile_prefix_chars```](https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars)
- json (or yaml) file. 

Parameters can be still be overriden in the command line argument list

The second approach can be use to introduce a deeper configuration structure where scenario, planning and visual output can be customized independently.

**Comment by arbimo** [comment]
Yes that's a good idea, I tend to prefer the json/yaml approach because
they are independent of any tool.
Json is in general more widespread and has better support while yaml is
much more readable, easier to write and support comments (last one is a
killer feature compared to json)

**Comment by rafael1193** [comment]
I pushed https://github.com/fire-rs-laas/fire-rs-saop/commit/a33330792ac6832e0b6f9a81481e60b149cbda08 that closes this issue using argparse fromfile_prefix_chars. It is a one-line solution that integrates with the parsing module, so no need to check manually if the specified arguments are ok: ArgParse does this for us.

The json conf. file can be added later, within a major revamp of the configuration system, without interfering with this approach.

**Comment by arbimo** [comment]
Great =)

The motivation for using json/yaml is mainly to externalize configuration for planning and benchmark generation. I might give it a try in the coming days since I will need to run many combinations of those.
