### ISSUE TITLE
Cleaner build process

### ISSUE THREAD

**Issue by arbimo** [fire-rs-laas/fire-rs-saop#8]
Currently, compiled artifacts (cython and C++ module) are copied into the source directory (as done by the _export_module_ target).
This facilitates development since the python scripts can be run directly and will find the compiled artifacts where they are expected.

This can be problematic when having multiple build types (e.g. Release and Debug) since they will target the same files inside the source directory.

A cleaner alternative would be to generate a new python package including the python sources and compiled artifacts inside the current build directory. We should then be able to install with the usual "make install".

The current behavior should remain available since it really helps in debugging Python code inside the IDE.

**Comment by rafael1193** [comment]
I just heard about ```python3 setup.py develop .``` that installs a python package in "develop" mode. Each time the sources are changed, the installed files get updated. (In fact it is better to use the equivalent  ```pip3 install -e .```, because pip is far more intelligent than the plain setup.py dealing with dependencies)

**Comment by arbimo** [comment]
"setup.py install" only compiles the Cython (.pyx) extension.
The main thing that would be to clean up is the generation of the shared library from C++ code for which the difference between debug and release mode is critical.
